### ISSUE TITLE
Access Koa context or session in nuxtServerInit

### ISSUE THREAD

**Issue by IlyaSemenov** [nuxt-community/koa-template#14]
Currently, `nuxtServerInit` receives a nuxt context which only includes node's `request` and `response`, and doesn't include Koa context. In particular, that means it's not possible to access `context.session` to determine the currently logged user (which is a must in most applications I believe).

I think that as this project is a bridge between Koa and Nuxt, the documentation should clearly explain how to access Koa context (or at least the session) in `nuxtServerInit`. I personally couldn't invent anything better than this:

```js

// server/index.js

app.use(async(ctx) => {
	ctx.status = 200 // koa defaults to 404 when it sees that status is unset
	ctx.req.session = ctx.session // for nuxtServerInit
	await nuxt.render(ctx.req, ctx.res)
})
```

and then:

```js
// store/index.js

export default () => new Vuex.Store({
	// ...
	actions: {
		nuxtServerInit ({ commit }, { req: { session } }) {
			if (session && session.userId) {
				commit('SET_USER', /*...*/)
			}
		},
```

but I'm not familiar with the framework so perhaps there is a more elegant way.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/koa-template/issues/c5">#c5</a>)</em></sub></div>

**Comment by dts** [comment]
Can you explain a bit about how you're getting this to work?  I'm getting a "cannot set headers after they are sent" errors, presumably because nuxt.render() makes sure the response is sent (because the internals of Nuxt don't really support Koa).  This is how I got things to work:

```js
  var sessionMiddleware = session(CONFIG,app);

  app.use(async (ctx, next) => {
    await sessionMiddleware(ctx,async () => {
      ctx.session.uuid = ctx.session.uuid || uuid();
    });

    await next();
  });
```

**Comment by IlyaSemenov** [comment]
@dts it was nothing special... usual boilerplate. In `server/index.js`, I added this:

```node
const passport = require('koa-passport')
passport.serializeUser((user, done) => { ... // I actually keep this in a separate file
passport.deserializeUser(async (id, done) => { ...
passport.use(new LocalStrategy((username, password, done) => { ...

app.use(passport.initialize())
app.use(passport.session())

app.use(...myroutes); // here I handle API call to login, see below.

// Start nuxt.js
async function start() {
	...
	app.use(async(ctx) => {
		ctx.status = 200 // koa defaults to 404 when it sees that status is unset
		ctx.req.session = ctx.session // for nuxtServerInit
		ctx.req.state = ctx.state // for nuxtServerInit
		await nuxt.render(ctx.req, ctx.res)
	})
```

In the routes:

```node
export const login = ctx => {
	return passport.authenticate('local', async (err, user, info, status) => {
		if (!user) {
			ctx.throw(401, info)
		}
		await ctx.login(user)
		ctx.body = await user.toJSON({accessor: user})
	})(ctx)
}
```

Then in `pages/secret.js`, I added:

```vue
<script>
	export default {
		middleware: 'auth',
	}
</script>
```

In `middleware/auth.js`:

```node
export default function ({ store, redirect, route }) {
	if (!store.state.authUser) {
		return redirect('/login', {next: route.path})
	}
}
```

in `store/index.js`:

```js
export default () => new Vuex.Store({

	state: {
		authUser: null
	},

	mutations: {
		SET_USER: function (state, user) {
			state.authUser = user
		}
	},

	actions: {
		async nuxtServerInit ({ commit }, { req: { state } }) {
			if (state.user) {
				const authUser = await state.user.toJSON({accessor: state.user})
				commit('SET_USER', authUser)
			}
		},
```

The session is only modified by koa-passport which runs before nuxt.

**Comment by dts** [comment]
Oh, so you're not using koa-session directly?

**Comment by IlyaSemenov** [comment]
No, but what's the difference if I write to the session directly, or if koa-passport writes to it? The point is that it happens earlier in the middleware stack, before knux.

**Comment by dts** [comment]
Agreed, but using bare koa-session did not work without my weird shim 😢

**Comment by dkushner** [comment]
Currently having the exact same issue as @dts. The fact that `nuxt.render()` closes the response seems like it would interfere with quite a lot of middleware. So why does it only appear to be koa-session?

**Comment by paulgv** [comment]
I'm also struggling quite a bit with this whole process. I'm trying to implement some flash messages but still can't figure out a solution with Nuxt + Koa.
Eg. I want to pass a "Bad credentials" message back to `nuxtServerInit` when Passport's validation fails but I'm still unable to remove the message from the session after Nuxt rendering...
