### ISSUE TITLE
TypeError: __WEBPACK_IMPORTED_MODULE_2_nuxt___default.a is not a constructor

### ISSUE THREAD

**Issue by PatrickSR** [nuxt-community/koa-template#16]
I create new project with this template, all the step can pass, but when I run `npm run dev`,console display "Compiled successfully in xxxxms",and then it will show "(node:24498) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: __WEBPACK_IMPORTED_MODULE_2_nuxt___default.a is not a constructor".

My node version is v7.10.1 and vue-cli version is v2.8.2.

**Comment by paulgv** [comment]
Answer here: https://github.com/nuxt/nuxt.js/issues/1167#issuecomment-318246732

**Comment by PatrickSR** [comment]
@paulgv It worked for me,thank you
