### ISSUE TITLE
Content Available over curl but not in browser

### ISSUE THREAD

**Issue by benfavre** [nuxt-community/koa-template#19]
- Browsers (any) load forever
- Curl can fetch the page

**Comment by paulgv** [comment]
I'm having the same issue when running `yarn build && yarn start`, pages never load in browser but Curl sees the content properly.
I don't have the issue when running `yarn dev`.
I noticed that `process.BROWSER_BUILD` does not seem to be set anymore, I had to use `process.browser` instead to prevent `vue-slider-component` from rendering server-side, I wonder if this blank page issue might be related to this change ?
