### ISSUE TITLE
How to disable server side babel transpilation?

### ISSUE THREAD

**Issue by RichAyotte** [nuxt-community/koa-template#26]
How do I disable the server side babel transpiling?

It is a big performance tax to pay during development.

```sh
yarn run v1.0.2
$ backpack dev

 DONE  Compiled successfully in 1401ms                                                                                                                                15:41:50

Server listening on 127.0.0.1:3000
Build completed in 79.273s

 DONE  Compiled successfully in 79278ms                                                                                                                               15:43:17

```
There seems to be a frontend build followed by a backend build which takes over a minute on my 6 core / 16GB RAM system. Any insight on what's building here?

**Comment by maodouchen** [comment]
i have the same problem?  do you have any solution?

**Comment by Atinux** [comment]
Hi,

You can remove `backpack.config.js` and update your `package.json` to run `node server/index.js` indead.
