### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by yoyoys** [nuxt-community/koa-template#37]
Node version: v9.5.0
Vue Cli: 2.9.3

I've just init this template by follow these steps: (alse tried by yarn)
`vue init nuxt-community/koa-template nuxt-koa-test`
`npm install`
`npm run dev`

and i got errors like this
```
 ERROR  Failed to compile with 1 errors                                                                                     

 error  in ./server/index.js

Module build failed: Error: Couldn't find preset "env" relative to directory
.....
```
```
/Users/Yoyo/github/nuxt-koa-test/build/main.js:216
}();
 ^
ReferenceError: regeneratorRuntime is not defined
    at /Users/Yoyo/github/nuxt-koa-test/build/main.js:135:46
```

---
And i tried to add a .babelrc file, like this:
```
{
  "presets": ["env"]
}
```
Then the first error message gone, but the second error still.
Is that a polyfill problem?

Thanks for help!

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/koa-template/issues/c21">#c21</a>)</em></sub></div>

**Comment by zachcb** [comment]
I just had the same issue. [This post helped me.](https://stackoverflow.com/questions/33527653/babel-6-regeneratorruntime-is-not-defined?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa)

Install these packages.
`npm install --save-dev babel-plugin-transform-runtime
 npm install --save babel-runtime
`

**.babelrc**
`{
  "presets": [
    [
      "env",
      {
        "modules": "commonjs"
      }
    ]
  ],
  "plugins": [
    "syntax-dynamic-import",
    ["transform-runtime", {
      "polyfill": false,
      "regenerator": true
    }]
  ]
}
`

**Comment by urbgimtam** [comment]
After updating from node 10 to node 12.18.0, this error started to appear in all upgraded projects.

It was enough to make "npm install --save babel-runtime".

**Comment by sgarner** [comment]
> `npm install --save babel-runtime`

This worked for me, but I also found I could `npm uninstall babel-runtime` afterwards and it remained fixed. Installing and then uninstalling it hoisted the `regenerator-runtime` dependency up to the top level in package-lock and node_modules, which was what was needed.

I expect a clean reinstall of node_modules would also have solved this.
